/** Compatibility imports; shared observed RPC response contracts live in contracts/. */
export type {
  QueueResponse,
  OnlineRival,
  RematchState,
  OnlineState,
  RoomCreateResponse,
  RoomPeekResponse,
  RoomJoinResponse,
  RematchResponse,
  LinkPlay,
  LinkData,
  LinkCompareData,
  DuelMeResponse,
  DuelTopEntry,
  SeasonMedal,
  SeasonChampion,
  SeasonRecord,
  SeasonInfoResponse,
  LinkMineCreated,
  LinkMineAnswered,
  DuelLinkMine,
  LinkStartResponse,
} from '../../../contracts/reto';
